from enum import Enum


class PolicyDecision(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    CONFIRMATION_REQUIRED = "CONFIRMATION_REQUIRED"


class ActionType(str, Enum):
    # Allowed Read & Analysis Actions
    READ_TRANSACTION = "READ_TRANSACTION"
    READ_EMAIL = "READ_EMAIL"
    CREATE_REPORT = "CREATE_REPORT"
    CREATE_EMAIL_DRAFT = "CREATE_EMAIL_DRAFT"
    RUN_RECONCILIATION = "RUN_RECONCILIATION"
    DETECT_DUPLICATES = "DETECT_DUPLICATES"
    DETECT_SUBSCRIPTIONS = "DETECT_SUBSCRIPTIONS"

    # Human-in-the-loop actions (Requires explicit user confirmation)
    SEND_EMAIL_TO_SELF = "SEND_EMAIL_TO_SELF"

    # Strictly Denied Actions (Security Boundaries)
    SEND_EMAIL_TO_MERCHANT = "SEND_EMAIL_TO_MERCHANT"
    SEND_EMAIL_TO_BANK = "SEND_EMAIL_TO_BANK"
    CANCEL_SUBSCRIPTION = "CANCEL_SUBSCRIPTION"
    TRANSFER_MONEY = "TRANSFER_MONEY"
    CHARGEBACK = "CHARGEBACK"
    LOCK_CARD = "LOCK_CARD"
    EXECUTE_TRANSACTION = "EXECUTE_TRANSACTION"
